# Tutorial Numpy

Numpy es una librería computacional para Python que es optimizada para operaciones en arreglos.

Para consultar la guía de referencia  completa de numpy, ver : https://numpy.org/

In [1]:
import numpy as np # Importación de la librería a usar y su respectivo alias np para facilitar su manipulación

# Creando Arreglos con Numpy

Los arreglos se pueden construir de diferentes maneras. Por ejemplo, se puede tomar una lista y convertirla en un arreglo de numpy:

In [2]:
myarray = np.array( [120, 2, 3, 4, 5, 7, 8] )

mylist = [1., 2., 3., 4.]
mynparray = np.array(mylist)

print("Arreglo myarray ")
print(myarray)
print("El arreglo es de tipo: ", end='')
print( myarray.dtype)

print("\nArreglo creado por lista")
print(mynparray)
print("El arreglo es de tipo: ", end='')
print( mynparray.dtype)

Arreglo myarray 
[120   2   3   4   5   7   8]
El arreglo es de tipo: int32

Arreglo creado por lista
[1. 2. 3. 4.]
El arreglo es de tipo: float64


Se puede inicializar un arreglo con todos los elementos en 1 o 0 con las funciones <b>*ones()*</b> y <b>*zeros()*</b>. Por ejemplo:<br>  
Arreglo unidimensional o vector con 1 fila y 4 columnas de <b>1</b>: 
$\left( \begin{array}{cccc}
1 & 1 & 1 & 1 \\
\end{array} \right)$

In [3]:
one_vector = np.ones(4)
print(one_vector)

[1. 1. 1. 1.]


Un arreglo bidimensional con 2 filas y 4 columnas de <b>1</b>:
$\left( \begin{array}{cccc}
1 & 1 & 1 & 1 \\
1 & 1 & 1 & 1\\
\end{array} \right)$

In [4]:
one2Darray = np.ones( (2, 4) )
print(one2Darray)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Arreglo unidimensional o vector con 1 fila y 4 columnas de <b>0</b>: 
$\left( \begin{array}{ccc}
0 & 0 & 0 & 0 \\
\end{array} \right)$

In [5]:
zero_vector = np.zeros(4)
print(zero_vector)

[0. 0. 0. 0.]


También se puede inicializar un arreglo vacío el cual será llenado con valores. Esta es la forma más rápida de inicializar arreglos en numpy con un tamaño fijo, sin embargo el programador se debe asegurar que se sustituyan todos los valores

In [6]:
empty_vector = np.empty(5)
print(empty_vector)

[7.56602523e-307 8.01089062e-307 2.11392033e-307 1.60216183e-306
 7.56602523e-307]


# Accediendo a los elementos de un arreglo

Para vectores se puede acceder al indice refiriendose a este con corchetes.<br>
* <b>Nota: Los indices en python inician en _0_</b>

In [7]:
mynparray

array([1., 2., 3., 4.])

In [8]:
mynparray[2]

3.0

Arreglos bidimensionales o matrices se pueden acceder de manera similar pero refiriendose al índice de la fila y de la columna separados por coma (,):  
* Primero declaramos la matriz con la variable $\text{my_matrix}$
* Luego imprimimos la matriz
* Por último, accedemos a los elementos de la fila 1 y columna 2 usando los índices $[0,1]$, lo que nos retorna el valor $2$.  
A continuación se presenta la matriz analizada.  
$\text{my_matrix = }\begin{pmatrix}
  1 & 2 & 3\\ 
  4 & 5 & 6
\end{pmatrix}$

In [9]:
my_matrix = np.array( [ [1, 2, 3] , [4, 5, 6] ] )
print(my_matrix)

[[1 2 3]
 [4 5 6]]


In [10]:
fila = 2
columna = 1
print(my_matrix[ fila - 1 , columna - 1 ])

4


Para acceder a porciones de la matriz podemos usar los dos puntos <b>(:)</b>. Por ejemplo, si queremos acceder los elementos de la columna 2 en todas sus filas podemos escribir:

In [11]:
columna = 2
print(my_matrix[ : , columna - 1 ])

[2 5]


Para acceder a todos los elementos de la fila 1 podemos escribir:

In [12]:
fila = 1
print(my_matrix[ fila - 1 , : ])

[1 2 3]


También se puede pasar una lista a los índices

In [13]:
# Creamos un vector de números aleatorios de la siguiente manera
fib_indices = np.array([1, 1, 2, 9])

random_vector = np.random.random(10)
print(random_vector)

[0.16899734 0.25629426 0.07240197 0.98329082 0.8255134  0.89800991
 0.45801739 0.49598403 0.0104918  0.66900093]


In [14]:
print(random_vector[fib_indices])

[0.25629426 0.25629426 0.07240197 0.66900093]


También se pueden usar los valores booleanos $True$ o $False$ para seleccionar elementos

In [15]:
my_vector = np.array([1, 2, 3, 4, 5, 6, 7, 8])

select_index = np.array([True, False, True, False, True, False, True, False])

print(my_vector[select_index])

[1 3 5 7]


* Para arreglos 2D se pueden seleccionar las columnas y filas específicas.  
* Pasando <b>(:)</b> selecciona todas las filas y todas las columnas.  
A continuación se presenta la matriz analizada.  
$\text{my_matrix = }\begin{pmatrix}
  1 & 2 & 3\\ 
  4 & 5 & 6
\end{pmatrix}$

In [16]:
my_matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
select_cols = np.array([True, False, True]) # columna 1 y 3
select_rows = np.array([False, True]) # Fila 2

In [18]:
print( my_matrix[ select_rows , : ] ) # Se selecciona toda la fila inferior

[[4 5 6]]


In [19]:
print( my_matrix[ : , select_cols ] ) # Se imprimen todas las filas y solo las columnas 1 y 3

[[1 3]
 [4 6]]


# Operaciones en arreglos

Se pueden usar las operaciones $ *, **, \, + \text{ y } -$ sobre arreglos de numpy, y estos operan <b>elemento a elemento</b>:
* Sea $ A = \begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix}$ y $ B = \begin{pmatrix}
    1.0\\
    -1.0\\
    1.0\\
    -1.0
\end{pmatrix}$

### Multiplicación elemento a elemento
$A*B = \begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} * \begin{pmatrix}
    1.0\\
    -1.0\\
    1.0\\
    -1.0
\end{pmatrix} = \begin{pmatrix}
    1.0\\
    -2.0\\
    3.0\\
    -4.0
\end{pmatrix}$

In [20]:
A  = np.array([1., 2., 3., 4.])
B  = np.array([1., -1., 1., -1.])
print( A*B )

[ 1. -2.  3. -4.]


### Potencia
$\text{A**2} = \begin{pmatrix}
    1.0^2\\
    2.0^2\\
    3.0^2\\
    4.0^2
\end{pmatrix} = \begin{pmatrix}
    1.0\\
    4.0\\
    9.0\\
    16.0
\end{pmatrix} $

In [23]:
print( A**2 )

[ 1.  4.  9. 16.]


### Resta
$A-B = \begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} - \begin{pmatrix}
    1.0\\
    -1.0\\
    1.0\\
    -1.0
\end{pmatrix} = \begin{pmatrix}
    0.0\\
    3.0\\
    2.0\\
    5.0
\end{pmatrix}$

In [24]:
print( A - B )

[0. 3. 2. 5.]


### Suma
$A+B = \begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} + \begin{pmatrix}
    1.0\\
    -1.0\\
    1.0\\
    -1.0
\end{pmatrix} = \begin{pmatrix}
    2.0\\
    1.0\\
    4.0\\
    3.0
\end{pmatrix}$

In [25]:
print(A + B)

[2. 1. 4. 3.]


### División
$A/3 = \begin{pmatrix}
    1.0/3.0\\
    2.0/3.0\\
    3.0/3.0\\
    4.0/3.0
\end{pmatrix} = \begin{pmatrix}
    0.33333333\\
    0.66666667\\
    1.0\\
    1.33333333
\end{pmatrix}$

In [26]:
print( A / 3. )

[0.33333333 0.66666667 1.         1.33333333]


In [27]:
(1/3)*A

array([0.33333333, 0.66666667, 1.        , 1.33333333])

### División con un vector elemento a elemento
* Sea $\text{C=}\begin{pmatrix}
    2.0\\
    3.0\\
    4.0\\
    5.0
\end{pmatrix}$

$A/C = \begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} / \begin{pmatrix}
    2.0\\
    3.0\\
    4.0\\
    5.0
\end{pmatrix} = \begin{pmatrix}
    1.0/2.0\\
    2.0/3.0\\
    3.0/4.0\\
    4.0/5.0
\end{pmatrix} = \begin{pmatrix}
    0.5\\
    0.66666667\\
    0.75\\
    0.8
\end{pmatrix}$

In [28]:
C = np.array([2., 3., 4., 5.])
print( A / C ) # = [1.0/2.0, 2.0/3.0, 3.0/4.0, 4.0/5.0]

[0.5        0.66666667 0.75       0.8       ]


Se puede realizar la suma de los elementos del vector usando la función $np.sum()$ y el promedio aritmético con $np.average()$

$ \text{A=}\begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} \rightarrow np.sum(A) = 1.0 + 2.0 + 3.0 + 4.0 = 10.0$

In [29]:
print(np.sum(A))

10.0


$ \text{A=}\begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} \rightarrow np.average(A) = (1.0 + 2.0 + 3.0 + 4.0) / 4.0 = 2.5$

In [30]:
print(np.average(A))

2.5


Podemos obtener la cantidad de elementos del vector con la función $len()$

In [31]:
len(A)

4

In [32]:
print( np.sum(A) / len(A) )

2.5


# El producto Punto

Una operación importante en algebra lineal es el producto punto $ \large{(\cdot)}$  
Cuando se computa el producto punto entre dos vectores, simplemente se multiplican elemento a elemento y se suma cada uno de los productos. En numpy esta operación se puede realizar con la función $np.dot()$
* Sea $\text{array1 =}\begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} \text{ y array2 =}\begin{pmatrix}
    2.0\\
    3.0\\
    4.0\\
    5.0
\end{pmatrix}$

$array1 \cdot array2 = \begin{pmatrix}
    1.0\\
    2.0\\
    3.0\\
    4.0
\end{pmatrix} {\large\cdot} \begin{pmatrix}
    2.0\\
    3.0\\
    4.0\\
    5.0
\end{pmatrix}\\
= 1.0*2.0 + 2.0*3.0 + 3.0*4.0 + 4.0*5.0 \\ 
= 2.0 + 6.0 + 12.0 + 20.0 = 40.0
$

In [33]:
array1 = np.array([1., 2., 3., 4.])
array2 = np.array([2., 3., 4., 5.])

print( np.dot(array1, array2) )

40.0


Utilizando la función $np.sum()$ y el operador $*$ que vimos anteriormente podemos obtener el mismo resultado

In [34]:
print( array1*array2 )

[ 2.  6. 12. 20.]


In [35]:
print( np.sum(array1*array2) )

40.0


El producto punto nos puede servir por ejemplo para calcular la magnitud de un vector que está ubicado en el espacio, matemáticamente sería:  
$\|x\|=\sqrt[2]{x_1^2+x_2^2+x_3^2}$

In [36]:
array1_mag = np.sqrt(np.dot(array1, array1))
print( array1_mag )

5.477225575051661


In [37]:
print( np.sqrt( np.sum( array1*array1 ) ) )

5.477225575051661


También se puede usar el producto punto para realizar el producto Matriz por vector de la siguiente manera.
* Sea una matriz $M_{m,n}$ con m filas y n columnas, y un vector $V_{n,1}$ con n elementos, tendremos:
$M_{4,2}=\begin{pmatrix}
  1 & 2\\ 
  3 & 4\\
  5 & 6\\
  7 & 8
\end{pmatrix}$, 
$V_{2,1}=\begin{pmatrix}
    0.4\\
    0.5
\end{pmatrix} \rightarrow M_{4,2} \cdot V_{2,1} = \begin{pmatrix}
    1.4\\
    3.2\\
    5.0\\
    6.8
\end{pmatrix}_{4,1}$

In [38]:
my_features = np.array( [ [1., 2.], [3., 4.], [5., 6.], [7., 8.] ] )
print(my_features)

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [39]:
my_weights = np.array( [0.4, 0.5] )
print(my_weights)

[0.4 0.5]


In [40]:
my_predictions = np.dot(my_features, my_weights) # Notar que el vector se posiciona a la derecha
print(my_predictions)

[1.4 3.2 5.  6.8]


De igual manera, si se tiene un vector $V_{1,n}$ con n elementos, que corresponden con la misma cantidad de filas de una matriz $M_{n,m}$tendremos:

In [42]:
my_matrix = my_features
my_array = np.array([0.3, 0.4, 0.5, 0.6])

In [45]:
print(np.dot(my_array, my_matrix))

[ 8.2 10. ]


# Multiplicación de matrices

Si tenemos dos matrices matrix_1 y matrix_2, donde el número de columnas de matrix_1 corresponde con el número de filas de matrix_2, entonces podemos usar la función $np.dot()$ para realizar el producto entre las matrices:  
$\text{matrix_1}=\begin{pmatrix}
  1 & 2 & 3\\ 
  4 & 5 & 6\\
\end{pmatrix}_{2,3} , \text{matrix_2}=\begin{pmatrix}
    1 & 2\\
    3 & 4\\
    5 & 6
\end{pmatrix}_{3,2} \rightarrow \text{matrix_1}_{2,3} \cdot \text{matrix_2}_{3,2} = \begin{pmatrix}
    22 & 28\\
    49 & 64
\end{pmatrix}_{2,2}$

In [46]:
matrix_1 = np.array([[1., 2., 3.],[4., 5., 6.]])
print(matrix_1)

[[1. 2. 3.]
 [4. 5. 6.]]


In [47]:
matrix_2 = np.array([[1., 2.], [3., 4.], [5., 6.]])
print(matrix_2)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


In [48]:
print( np.dot( matrix_1, matrix_2 ) )

[[22. 28.]
 [49. 64.]]


Podemos utilizar también el operador $@$ para el producto matricial

In [49]:
print( matrix_1@matrix_2 )

[[22. 28.]
 [49. 64.]]
